specVersion: 0.2.0
name: darwinia
version: 1.0.0
description: ''
repository: git@github.com:darwinia-network/subql-wormhole.git
schema:
  file: ./schema.graphql
network:
  genesisHash: '0xf37f31c4481e3c937ad40b672c561d0c0b1fb70b40e51a0d56dad30d60e4db58'
  endpoint: wss://rpc.darwinia.network/
dataSources:
  - kind: substrate/Runtime
    startBlock: 1
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleBlock
          kind: substrate/BlockHandler
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: balances
            method: Deposit
        - handler: handleCall
          kind: substrate/CallHandler
