specVersion: 0.2.0
name: crab
version: 1.0.0
description: ''
repository: git@github.com:darwinia-network/subql-wormhole.git
schema:
  file: ./schema.graphql
network:
  genesisHash: '0x34f61bfda344b3fad3c3e38832a91448b3c613b199eb23e5110a635d71c13c65'
  endpoint: wss://crab-rpc.darwinia.network/
dataSources:
  - kind: substrate/Runtime
    startBlock: 1
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleBlock
          kind: substrate/BlockHandler
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: balances
            method: Deposit
        - handler: handleCall
          kind: substrate/CallHandler
